const host = "http://localhost:8082"
export const urls = {
    saveGateway: host + "/krakend/saveKrakendJson",
    // addEndpoint:host+"/krakend/addendpoints",
    updateEndpoint: host + "/krakend/updateEndpoint",
    getEndpointById: host + "/krakend/getKrakendJson",
    // updateBackend:host+"/krakend/updateBackendOfEndpoint",
    updateKrakend: host + "/krakend/updateKrakendJson",
    getGatewayCards: host + "/krakend/getKrakendJsonCards",
    getUser: host + "/user/getUser",
    deployFile: host + "/krakend/krakendFile",
    getEndpointCards: host + "/krakend/endpoint/getEndpointCards",
    addEndpoint: host + "/krakend/endpoint/addendpoint",
    linkEndpoint: host + "/krakend/linkEndpoint",
    addbackend: host + "/krakend/endpoint/backend/addBackendToEndpoint",
    getEndpoint: host + "/krakend/endpoint/getEndpoint",
    updateBackend: host + "/krakend/endpoint/backend/updateBackendOfEndpoint",
    addParametersByEndpoint: host + "/krakend/endpoint/addParameterForwarding",
    addUpdateThrottling: host + "/krakend/endpoint/addOrUpdateThrottling",
    addResponse: host + "/krakend/endpoint/addOrUpdateResponseManipulation",
    addPolicies:host +"/krakend/endpoint/addOrUpdatePolices",
    addConnectivity : host + "/krakend/endpoint/addOrUpdateConnectivityOptions",
    addOpenAPI:host +"/krakend/endpoint/addOrUpdateOpenApi",
    deleteEndpoint:host+"/krakend/endpoint/deletedEndpoint",
    addOrUpdateTelemetryMoesifUrl:host +"/krakend/extraconfig/monetization/addOrUpdateTelemetryMoesif",
    deleteBackend:host+"/krakend/endpoint/backend/deletedBackend",
    addOrUPdateHttpSecurity :host + "/krakend/extraconfig/httpSecurity/addOrUpdateHttpSecurity",
    addOrUpdateServiceSetting: host + "/krakend/extraconfig/serviceSetting/addOrUpdateServiceSetting",
    getSecurityAuth: host + "/globalSecurity/getGlobalSettings",
    saveSecurityAuthValidator: host + "/globalSecurity/saveAuthValidatorGlobal",
    saveSecurityAuthSigner: host + "/globalSecurity/saveAuthSignerGlobal",
    saveSecurityAuthBasic: host + "/globalSecurity/saveAuthBasicGlobal",
    saveSecurityAuthApiKey : host + "/globalSecurity/saveAuthApiKeysGlobal",
    createConsumer: host + "/user/createConsumer",
    getConsumer: host + "/user/getConsumers",
    deleteConsumer:host + "/user/deleteConsumer",
    createApplication: host + "/clients/openid/createApplication",
    getApplications: host + "/clients/openid/getApplications",
    deleteApplication: host + "/clients/openid/deleteApplication",

    checkContextPath:host+"/krakend/endpoint/checkEndpointContext",
    subscribeToApplication:host+"/clients/openid/subscribeToApplication",
    unsubscribeToApplication:host+"/clients/openid/unsubscribeToApplication"
}